random_seed: 42

reports_file_train: ../data/csv_dir/reports/train_reports.csv
reports_file_valid: ../data/csv_dir/reports/train_reports.csv
metadata_train: ../data/csv_dir/metadata/train_metadata.csv
use_seg: True
data_train: ../data/data_dir/sub30_dataset_train
data_valid: ../data/data_dir/sub30_dataset_val
seg_data_train: ../data/seg_data_dir/total_data/train
seg_data_valid: ../data/seg_data_dir/total_data/valid
seg_mask_train: ../data/seg_data_dir/total_mask/train
seg_mask_valid: ../data/seg_data_dir/total_mask/valid
balance_report_seg: 1.0
labels: ../data/csv_dir/labels/train_predicted_labels.csv
batch_size: 2
results_folder: ./output_train_scratch
num_train_steps: 100
num_workers: 0
gradient_accumulation_steps: 1


project_name: ct-clip-vit-seg
exp_name: train_from_scratch_with_seg_debug

arch_name: CTViT3D # this is vit_vanilla_3D with support of segmentation head

use_flash_attention: True


# arch
dim: 768
image_size: 480
patch_size: 20
temporal_size: 240
temporal_patch_size: 10
transformer_blocks: 8
dim_head: 32
heads: 8

# seg head
seg_head_n_layers: 2
seg_head_layer_type: mlp
seg_head_in_dim: 768
seg_head_mid_dim: 128
seg_head_out_dim: 22 # 22 labels to be segmented, but the dim is 22 * patch volume (20, 20, 10)

balance_report_seg: 1