random_seed: 42

reports_file_train: /mnt/input/CT-RATE/organized_dataset/csv_dir/reports/train_reports.csv
reports_file_valid: /mnt/input/CT-RATE/organized_dataset/csv_dir/reports/validation_reports.csv
metadata_train: /mnt/input/CT-RATE/organized_dataset/csv_dir/metadata/train_metadata.csv
use_seg: True
data_train: /mnt/input/CT-RATE/sub_dataset/prepocessed_float32_divide_5/divide_0/train
data_valid: /mnt/input/CT-RATE/sub_dataset/prepocessed_float32_divide_5/divide_0/val
seg_data_train: /mnt/input/TotalSegmentator/preprocessed_data
# tmp no valid in code, todo: change to correct version in future versions
seg_data_valid: /mnt/input/TotalSegmentator/preprocessed_data
seg_mask_train: /mnt/input/TotalSegmentator/preprocessed_mask
seg_mask_valid: /mnt/input/TotalSegmentator/preprocessed_mask
labels: /mnt/input/CT-RATE/organized_dataset/csv_dir/labels/train_predicted_labels.csv
batch_size: 4
results_folder: ./output_train_scratch
num_train_steps: 40001
num_workers: 16
gradient_accumulation_steps: 2

project_name: ct-clip-vit-seg
exp_name: train_from_scratch_vit_hpc_1_dim_384_div0

arch_name: CTViT3D # this is vit_vanilla_3D

use_flash_attention: True


# arch
dim: 384
image_size: 480
patch_size: 20
temporal_size: 240
temporal_patch_size: 10
transformer_blocks: 8
dim_head: 32
heads: 8

# seg head
seg_head_n_layers: 2
seg_head_layer_type: mlp
seg_head_in_dim: 768
seg_head_mid_dim: 128
seg_head_out_dim: 22 # 22 labels to be segmented, but the dim is 22 * patch volume (20, 20, 10)

balance_report_seg: 1